build:	 
	nasm -f elf p.asm
	ld -m elf_i386 p.o -o ../../bin/practica8.exe ../../lib/libpc_io.a
run:
	./../../bin/practica8.exe

buildd:	 
	nasm -f elf pp.asm
	ld -m elf_i386 pp.o -o ../../bin/practica8.exe ../../lib/libpc_io.a
runn:
	./../../bin/practica8.exe